[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hibou"
version = "0.1.0"
description = "A Foundational Vision Transformer for Histopathology"
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["hibou"]
