tissue_types:
  "Adrenal_gland": 0
  "Bile-duct": 1
  "Bladder": 2
  "Breast": 3
  "Cervix": 4
  "Colon": 5
  "Esophagus": 6
  "HeadNeck": 7
  "Kidney": 8
  "Liver": 9
  "Lung": 10
  "Ovarian": 11
  "Pancreatic": 12
  "Prostate": 13
  "Skin": 14
  "Stomach": 15
  "Testis": 16
  "Thyroid": 17
  "Uterus": 18

nuclei_types:
  "Background": 0
  "Neoplastic": 1
  "Inflammatory": 2
  "Connective": 3
  "Dead": 4
  "Epithelial": 5
